[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --strict-markers
    --alluredir=allure-results
    -n auto
markers =
    api: API automation tests
    ui: UI automation tests
    smoke: Critical smoke tests
    regression: Regression tests
